# Generated by Django 2.0.5 on 2018-08-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('departement', models.CharField(choices=[('Gestion', 'Gestion'), ('Informatique', 'Informatique'), ('Langues', 'Langues'), ('Polytechnique', 'Polytechnique'), ('Qualité', 'Qualité'), ('Transport et Logistique', 'Transport et Logistique')], help_text='veuillez selectionner un Departement', max_length=255)),
                ('option', models.CharField(choices=[('Banque Finance Assurance', 'Banque Finance Assurance'), ('Commerce International', 'Commerce International'), ('Comptabilité Gestion Entreprise', 'Comptabilité Gestion Entreprise'), ('Electricité Industrielle', 'Electricité Industrielle'), ('Informatique de Gestion', 'Informatique de Gestion'), ('Gestion des Ressources Humaines', 'Gestion des Ressources Humains'), ('Langues et Affaires', 'Langues et Affaires'), ('Maintenance Industrielle', 'Maintenance Industrielle'), ('Management,Qualité,Securité et Environnement', 'Management,Qualité,Securité et Environnement'), ('Secretariat de Direction Bilingue', 'Secretariat de Direction Bilingue'), ('Transport et Logistique', 'Transport et Logistique'), ('Télécommunications et Reseaux', 'Télécommunications et Reseaux')], help_text='veuillez selectionner une Option', max_length=255, primary_key=True, serialize=False)),
                ('titre', models.CharField(help_text='veuillez selectionner le titre du document', max_length=100)),
                ('auteur', models.CharField(max_length=90)),
                ('image', models.FileField(upload_to='Reperttoire_Images')),
                ('fichier', models.FileField(upload_to='Reperttoire_Documets')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
