# Generated by Django 2.0.5 on 2018-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='Repertoire_Images/depdefault.jpeg', upload_to='Repertoire_Images'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='image',
            field=models.FileField(default='Repertoire_Images/filieredefaut.jpg', upload_to='Repertoire_Images'),
        ),
    ]
