# Generated by Django 2.0.5 on 2018-07-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eces.Categorie'),
        ),
    ]
