# Generated by Django 2.0.5 on 2018-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0002_auto_20180901_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ('libelle',), 'verbose_name_plural': 'DEPARTEMENTS'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'DOCUMENTS'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ('libelle',), 'verbose_name_plural': 'FILIERES'},
        ),
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='bibliotheque/images_defaut/depdefault1.jpeg', upload_to='Repertoire_Images'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='image',
            field=models.FileField(default='Repertoire_Images/filieredefaut1.jpg', upload_to='Repertoire_Images'),
        ),
    ]
