# Generated by Django 2.0.5 on 2018-08-10 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0002_document_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='departement',
            name='image',
            field=models.FileField(default=datetime.datetime(2018, 8, 10, 10, 36, 10, 769799, tzinfo=utc), upload_to='Repertoire_Images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiere',
            name='image',
            field=models.FileField(default=datetime.datetime(2018, 8, 10, 10, 36, 28, 640441, tzinfo=utc), upload_to='Repertoire_Images'),
            preserve_default=False,
        ),
    ]
