# Generated by Django 2.0.5 on 2018-09-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0003_auto_20180903_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='../images_defaut/depdefault1.jpeg', upload_to='Repertoire_Images'),
        ),
    ]
