# Generated by Django 2.0.5 on 2018-03-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0004_auto_20180326_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='164484340.jpg', upload_to='Repertoire_Images'),
        ),
    ]
