# Generated by Django 2.0.5 on 2018-03-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0005_auto_20180327_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='/multimedia/Repertoire_Images/164484340.jpg', upload_to='Repertoire_Images'),
        ),
    ]
