# Generated by Django 2.0.5 on 2018-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0006_auto_20180327_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='/multimedia/Repertoire_Images/poi.jpg', upload_to='Repertoire_Images'),
        ),
    ]
