# Generated by Django 2.0.5 on 2018-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0007_auto_20180816_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(upload_to='Repertoire_Images'),
        ),
    ]
