# Generated by Django 2.0.5 on 2018-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0010_auto_20180816_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='/Repertoire_Images/default.jpg', upload_to='Repertoire_Images'),
        ),
    ]
