# Generated by Django 2.0.5 on 2018-08-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0012_auto_20180816_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='image',
            field=models.FileField(default='Repertoire_Images/images.jpeg', upload_to='Repertoire_Images'),
        ),
    ]
